chess_test: chess_test.cpp chess.cpp chess.h
	clang++ -std=c++20 -O2 -Wall chess_test.cpp chess.cpp -o chess_test

sovereign_chess_test: sovereign_chess_test.cpp sovereign_chess.h sovereign_chess.cpp chess.cpp chess.h
	clang++ -std=c++20 -O2 -Wall sovereign_chess_test.cpp sovereign_chess.cpp chess.cpp -o sovereign_chess_test